# Generated by Django 2.2.6 on 2020-03-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
