# Generated by Django 2.2.6 on 2020-03-14 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sheet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.TextField()),
                ('q2', models.TextField()),
                ('q3', models.TextField()),
                ('q4', models.TextField()),
                ('q5', models.TextField()),
                ('codecademy', models.TextField(choices=[('Y', 'yes'), ('N', 'no')], max_length=1)),
                ('first_pf', models.TextField(choices=[('P', '1차 합격'), ('F', '불합격')], max_length=1, null=True)),
                ('final_pf', models.TextField(choices=[('P', '최종 합격'), ('F', '불합격')], max_length=1, null=True)),
                ('signup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signup_user', to='sheet.Signup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
