# Generated by Django 2.2.6 on 2020-03-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='interview',
            field=models.TextField(choices=[('on', '온라인 면접'), ('off', '오프라인 면접')], max_length=3, null=True),
        ),
    ]
